# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c4cefa453b75606ce408a3f6d668bd1318e7df0cf4f11f63519973faf6178d958fa22aad11c0b32d06ff5ac52926b88d0ae05aef36786f804917bf255b8b873

test:
  secret_key_base: 3676c90716900d4adb95dcb4f2b582f81768fc4d6292608e1454289ea3c5b2512d6ea234076198fbfc465f52497d7fd917628244ea97cf136058221b96692584

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
